/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

/** RMS energy of interleaved s16le PCM (0..32768 scale). Used for energy VAD. */
export declare function pcmRms(pcm: Buffer): number
/** True when RMS is at or above the speech threshold (default 500 matches TS SilenceSegmenter). */
export declare function isSpeechFrame(pcm: Buffer, energyThreshold: number): boolean
/** Package probe for loaders / health checks. */
export declare function nativeAudioBackend(): string
/** Opus encoder/decoder pair backed by system libopus (PR-B4). */
export declare class NativeOpus {
  /** Create a native Opus codec. Defaults match TeamSpeak music: 48kHz stereo, 20ms frames. */
  constructor(sampleRate: number, channels: number)
  /**
   * Set target Opus bitrate in bits/second.
   *
   * `bps <= 0` selects libopus Auto. Values are clamped to the Opus-meaningful
   * range (500–512000). Used by the dashboard music stream bitrate slider so
   * Starlink/uplink-constrained hosts can trade quality for bandwidth.
   */
  setBitrateBps(bps: number): void
  /** Encode interleaved s16le PCM to a single Opus packet. */
  encode(pcm: Buffer): Buffer
  /** Decode one Opus packet to interleaved s16le PCM. */
  decode(opus: Buffer): Buffer
}
