// Copyright (c) 2026 Lane Ambrose
// SPDX-License-Identifier: MIT

//! Playback blacklist + protected artists. Port of
//! `bot/src/music/playback-blacklist.ts`. Matching is multi-key: opaque id,
//! YouTube video id, and a normalized name+artist fingerprint.

use std::sync::Arc;

use mp_db::Database;

pub const CONTENT_KEY_PREFIX: &str = "content:";

#[derive(Debug, Clone)]
pub struct BlacklistEntry {
    pub track_key: String,
    pub platform: Option<String>,
    pub name: Option<String>,
    pub artist: Option<String>,
    pub reason: Option<String>,
    pub created_by: Option<String>,
    pub created_at: i64,
}

pub fn normalize_blacklist_text(raw: &str) -> String {
    let mut s = raw.to_lowercase();
    for pat in [
        "(official video)",
        "(official music video)",
        "(official audio)",
        "(official lyric video)",
        "[official video]",
    ] {
        s = s.replace(pat, " ");
    }
    for word in [
        "official hd music video",
        "official music video",
        "official audio",
        "official lyric video",
        "lyrics",
        "lyric",
        "visualizer",
        "remastered",
        "remaster",
        "hq",
        "hd",
        "4k",
    ] {
        s = replace_word(&s, word);
    }
    s = s.replace('*', "");
    s.chars()
        .map(|c| if c.is_alphanumeric() || c.is_whitespace() { c } else { ' ' })
        .collect::<String>()
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ")
}

fn replace_word(s: &str, word: &str) -> String {
    let mut out = String::new();
    let lower = s.to_lowercase();
    let mut i = 0;
    let bytes = lower.as_bytes();
    let w = word.as_bytes();
    while i < bytes.len() {
        if bytes[i..].starts_with(w) {
            let before_ok = i == 0 || !bytes[i - 1].is_ascii_alphanumeric();
            let after = i + w.len();
            let after_ok = after >= bytes.len() || !bytes[after].is_ascii_alphanumeric();
            if before_ok && after_ok {
                out.push(' ');
                i = after;
                continue;
            }
        }
        out.push(lower[i..].chars().next().unwrap());
        i += lower[i..].chars().next().unwrap().len_utf8();
    }
    out
}

pub fn normalize_blacklist_artist(raw: &str) -> String {
    let mut s = normalize_blacklist_text(raw);
    for word in [
        "official",
        "topic",
        "vevo",
        "records",
        "music",
        "channel",
        "auto-generated",
        "autogenerated",
    ] {
        s = replace_word(&s, word);
    }
    s.split_whitespace().collect::<Vec<_>>().join(" ")
}

fn collapse_for_fingerprint(s: &str) -> String {
    s.chars()
        .filter(|c| !matches!(c, 'a' | 'e' | 'i' | 'o' | 'u' | 'y'))
        .collect()
}

pub fn blacklist_content_key(name: Option<&str>, artist: Option<&str>) -> Option<String> {
    let mut n = normalize_blacklist_text(name.unwrap_or(""));
    if n.len() < 3 {
        return None;
    }
    let a = normalize_blacklist_artist(artist.unwrap_or(""));
    if !a.is_empty() {
        let prefix = format!("{a} ");
        if n.starts_with(&prefix) {
            n = n[prefix.len()..].trim().to_string();
        }
    }
    if n.len() < 3 {
        return None;
    }
    let n_key = collapse_for_fingerprint(&n);
    let a_key = if a.is_empty() {
        String::new()
    } else {
        collapse_for_fingerprint(&a)
    };
    if n_key.len() < 3 {
        return None;
    }
    Some(if a_key.is_empty() {
        format!("{CONTENT_KEY_PREFIX}{n_key}")
    } else {
        format!("{CONTENT_KEY_PREFIX}{n_key}|{a_key}")
    })
}

/// 11-char YouTube id from a URL or bare id.
pub fn extract_video_id(raw: &str) -> Option<String> {
    let s = raw.trim();
    if s.len() == 11 && s.chars().all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_') {
        return Some(s.to_string());
    }
    for key in ["v=", "youtu.be/", "/shorts/", "/embed/"] {
        if let Some(i) = s.find(key) {
            let rest = &s[i + key.len()..];
            let id: String = rest
                .chars()
                .take_while(|c| c.is_ascii_alphanumeric() || *c == '-' || *c == '_')
                .take(11)
                .collect();
            if id.len() == 11 {
                return Some(id);
            }
        }
    }
    None
}

pub fn is_ban_protected(
    name: Option<&str>,
    artist: Option<&str>,
    protected_artists: &[String],
) -> bool {
    if protected_artists.is_empty() {
        return false;
    }
    let hay = format!("{} {}", name.unwrap_or(""), artist.unwrap_or(""))
        .to_lowercase()
        .split_whitespace()
        .collect::<Vec<_>>()
        .join(" ");
    if hay.is_empty() {
        return false;
    }
    protected_artists.iter().any(|raw| {
        let needle = raw.to_lowercase().split_whitespace().collect::<Vec<_>>().join(" ");
        !needle.is_empty() && hay.contains(&needle)
    })
}

pub fn ban_protected_message(name: Option<&str>, artist: Option<&str>) -> String {
    let parts: Vec<&str> = [name, artist]
        .into_iter()
        .flatten()
        .filter(|s| !s.is_empty())
        .collect();
    let label = if parts.is_empty() {
        "that track".to_string()
    } else {
        parts.join(" — ")
    };
    format!("Not a chance — {label} is on the protected list.")
}

pub struct PlaybackBlacklist {
    db: Arc<Database>,
    protected: Arc<dyn Fn() -> Vec<String> + Send + Sync>,
    now: Arc<dyn Fn() -> i64 + Send + Sync>,
}

impl PlaybackBlacklist {
    pub fn new(db: Arc<Database>, protected: impl Fn() -> Vec<String> + Send + Sync + 'static) -> Self {
        Self {
            db,
            protected: Arc::new(protected),
            now: Arc::new(|| {
                std::time::SystemTime::now()
                    .duration_since(std::time::UNIX_EPOCH)
                    .unwrap()
                    .as_millis() as i64
            }),
        }
    }

    pub fn with_now(mut self, now: impl Fn() -> i64 + Send + Sync + 'static) -> Self {
        self.now = Arc::new(now);
        self
    }

    fn protected_artists(&self) -> Vec<String> {
        (self.protected)()
    }

    pub fn has_key(&self, track_key: &str) -> bool {
        if track_key.is_empty() {
            return false;
        }
        self.db
            .with_conn(|conn| {
                let n: i64 = conn.query_row(
                    "SELECT 1 FROM playback_blacklist WHERE track_key = ?1 LIMIT 1",
                    [track_key],
                    |_| Ok(1),
                )
                .unwrap_or(0);
                Ok(n == 1)
            })
            .unwrap_or(false)
    }

    fn insert_key(
        &self,
        track_key: &str,
        platform: Option<&str>,
        name: Option<&str>,
        artist: Option<&str>,
        reason: Option<&str>,
        created_by: Option<&str>,
        created_at: i64,
    ) {
        if track_key.is_empty() {
            return;
        }
        let _ = self.db.with_conn(|conn| {
            conn.execute(
                "INSERT INTO playback_blacklist (track_key, platform, name, artist, reason, created_by, created_at)
                 VALUES (?1, ?2, ?3, ?4, ?5, ?6, ?7)
                 ON CONFLICT(track_key) DO UPDATE SET
                   platform = COALESCE(excluded.platform, playback_blacklist.platform),
                   name = COALESCE(excluded.name, playback_blacklist.name),
                   artist = COALESCE(excluded.artist, playback_blacklist.artist),
                   reason = COALESCE(excluded.reason, playback_blacklist.reason),
                   created_by = COALESCE(excluded.created_by, playback_blacklist.created_by),
                   created_at = excluded.created_at",
                rusqlite::params![
                    track_key,
                    platform,
                    name,
                    artist,
                    reason,
                    created_by,
                    created_at
                ],
            )?;
            Ok(())
        });
    }

    pub fn add(
        &self,
        track_key: &str,
        platform: Option<&str>,
        name: Option<&str>,
        artist: Option<&str>,
        reason: Option<&str>,
        created_by: Option<&str>,
    ) -> Result<BlacklistEntry, String> {
        let track_key = track_key.trim();
        if track_key.is_empty() {
            return Err("trackKey required".into());
        }
        if is_ban_protected(name, artist, &self.protected_artists()) {
            return Err(ban_protected_message(name, artist));
        }
        let created_at = (self.now)();
        self.insert_key(track_key, platform, name, artist, reason, created_by, created_at);
        if let Some(vid) = extract_video_id(track_key) {
            if vid != track_key {
                self.insert_key(
                    &vid,
                    platform.or(Some("youtube")),
                    name,
                    artist,
                    reason,
                    created_by,
                    created_at,
                );
            }
        }
        if let Some(from_name) = embedded_video_id(name.unwrap_or("")) {
            if from_name != track_key {
                self.insert_key(
                    &from_name,
                    platform.or(Some("youtube")),
                    name,
                    artist,
                    reason,
                    created_by,
                    created_at,
                );
            }
        }
        if let Some(fp) = blacklist_content_key(name, artist) {
            if fp != track_key {
                self.insert_key(&fp, platform, name, artist, reason, created_by, created_at);
            }
        }
        Ok(BlacklistEntry {
            track_key: track_key.to_string(),
            platform: platform.map(str::to_string),
            name: name.map(str::to_string),
            artist: artist.map(str::to_string),
            reason: reason.map(str::to_string),
            created_by: created_by.map(str::to_string),
            created_at,
        })
    }

    pub fn remove(&self, track_key: &str) -> bool {
        let key = track_key.trim();
        if key.is_empty() {
            return false;
        }
        let row = self.db.with_conn(|conn| {
            let mut stmt = conn.prepare(
                "SELECT track_key, name, artist FROM playback_blacklist WHERE track_key = ?1 LIMIT 1",
            )?;
            let r = stmt
                .query_row([key], |row| {
                    Ok((
                        row.get::<_, String>(0)?,
                        row.get::<_, Option<String>>(1)?,
                        row.get::<_, Option<String>>(2)?,
                    ))
                })
                .ok();
            Ok(r)
        }).ok().flatten();

        let mut removed = self.delete_key(key);
        if let Some(vid) = extract_video_id(key) {
            if vid != key {
                removed = self.delete_key(&vid) || removed;
            }
        }
        let (name, artist) = row
            .as_ref()
            .map(|(_, n, a)| (n.clone(), a.clone()))
            .unwrap_or((None, None));
        if let Some(from_name) = name.as_deref().and_then(embedded_video_id) {
            removed = self.delete_key(&from_name) || removed;
        }
        if let Some(fp) = blacklist_content_key(name.as_deref(), artist.as_deref()) {
            removed = self.delete_key(&fp) || removed;
        }
        if row.is_none() {
            let as_fp = if key.starts_with(CONTENT_KEY_PREFIX) {
                Some(key.to_string())
            } else {
                blacklist_content_key(Some(key), None)
            };
            if let Some(fp) = as_fp {
                removed = self.delete_key(&fp) || removed;
            }
        }
        removed
    }

    fn delete_key(&self, key: &str) -> bool {
        self.db
            .with_conn(|conn| {
                let n = conn.execute("DELETE FROM playback_blacklist WHERE track_key = ?1", [key])?;
                Ok(n > 0)
            })
            .unwrap_or(false)
    }

    pub fn is_blacklisted(&self, id: Option<&str>, name: Option<&str>, artist: Option<&str>) -> bool {
        if is_ban_protected(name, artist, &self.protected_artists()) {
            return false;
        }
        if let Some(id) = id {
            if self.has_key(id) {
                return true;
            }
            if let Some(vid) = extract_video_id(id) {
                if vid != id && self.has_key(&vid) {
                    return true;
                }
            }
        }
        if let Some(n) = name {
            if let Some(vid) = embedded_video_id(n) {
                if self.has_key(&vid) {
                    return true;
                }
            }
        }
        if let Some(fp) = blacklist_content_key(name, artist) {
            if self.has_key(&fp) {
                return true;
            }
        }
        false
    }

    pub fn list(&self) -> Vec<BlacklistEntry> {
        self.db
            .with_conn(|conn| {
                let mut stmt = conn.prepare(
                    "SELECT track_key, platform, name, artist, reason, created_by, created_at
                     FROM playback_blacklist ORDER BY created_at DESC",
                )?;
                let rows = stmt.query_map([], |row| {
                    Ok(BlacklistEntry {
                        track_key: row.get(0)?,
                        platform: row.get(1)?,
                        name: row.get(2)?,
                        artist: row.get(3)?,
                        reason: row.get(4)?,
                        created_by: row.get(5)?,
                        created_at: row.get(6)?,
                    })
                })?;
                let mut out = Vec::new();
                for r in rows.flatten() {
                    if !r.track_key.starts_with(CONTENT_KEY_PREFIX) {
                        out.push(r);
                    }
                }
                Ok(out)
            })
            .unwrap_or_default()
    }
}

fn embedded_video_id(name: &str) -> Option<String> {
    let start = name.find('[')?;
    let end = name[start + 1..].find(']')?;
    let inner = &name[start + 1..start + 1 + end];
    if inner.len() == 11
        && inner
            .chars()
            .all(|c| c.is_ascii_alphanumeric() || c == '-' || c == '_')
    {
        Some(inner.to_string())
    } else {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;

    fn store() -> PlaybackBlacklist {
        let db = Arc::new(mp_db::Database::open_in_memory().unwrap());
        PlaybackBlacklist::new(db, Vec::new).with_now(|| 1_700_000_000_000)
    }

    #[test]
    fn add_list_remove() {
        let bl = store();
        bl.add("abc123", Some("local"), Some("Tune"), Some("A"), None, None)
            .unwrap();
        assert!(bl.has_key("abc123"));
        assert!(bl.is_blacklisted(Some("abc123"), None, None));
        assert_eq!(bl.list().len(), 1);
        assert!(bl.remove("abc123"));
        assert!(!bl.has_key("abc123"));
    }

    #[test]
    fn fingerprint_blocks_reseed() {
        let bl = store();
        bl.add(
            "cee102bedd919fafc618743f59ce6346b0ebbb53",
            Some("local"),
            Some("\"Yacht Rock\" Is Bullsh*t"),
            Some("Rick Beato"),
            None,
            None,
        )
        .unwrap();
        assert!(bl.is_blacklisted(
            Some("kEYUw2kiRfc"),
            Some("\"Yacht Rock\" Is Bullsh*t"),
            Some("Rick Beato")
        ));
        assert!(bl.is_blacklisted(
            Some("otherid12345"),
            Some("\"Yacht Rock\" Is Bullsh*t (Official Video)"),
            Some("Rick Beato")
        ));
        assert!(bl.is_blacklisted(
            Some("kEYUw2kiRfc"),
            Some("Yacht Rock Is Bullshit"),
            Some("Rick Beato - Topic")
        ));
    }

    #[test]
    fn protected_artist_wins() {
        let db = Arc::new(mp_db::Database::open_in_memory().unwrap());
        let bl = PlaybackBlacklist::new(db, || vec!["Ella Langley".into()]);
        let err = bl
            .add(
                "x",
                Some("local"),
                Some("Choosin Texas"),
                Some("Ella Langley"),
                None,
                None,
            )
            .unwrap_err();
        assert!(err.contains("protected"));
        assert!(!bl.is_blacklisted(
            Some("x"),
            Some("Choosin Texas"),
            Some("Ella Langley")
        ));
    }
}
