#!/usr/bin/env bash
# Set up an on-device "wiki-as-code" doctrine repo (ROADMAP Phase 6, canonical
# ingestion path). Members push Markdown doctrine to a bare git repo over
# SSH/LAN; a post-receive hook mirrors the .md files into the bot's doctrine dir,
# and the running bot's watcher auto-reindexes them into the knowledge base.
#
# Usage:
#   ./scripts/setup-doctrine-repo.sh [options] [BARE_REPO] [DOCTRINE_DIR]
#
# Defaults:
#   BARE_REPO    = ~/doctrine.git
#   DOCTRINE_DIR = <repo>/bot/data/doctrine
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
FORCE=0
DRY_RUN=0

usage() {
  cat <<EOF
Set up a bare doctrine git repo with post-receive → bot/data/doctrine sync.

  $0 [options] [BARE_REPO] [DOCTRINE_DIR]

Options:
  --force       Overwrite an existing post-receive hook
  --dry-run     Print actions without writing
  -h, --help    Show this help
EOF
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --force) FORCE=1; shift ;;
    --dry-run) DRY_RUN=1; shift ;;
    -h|--help) usage; exit 0 ;;
    -*) echo "Unknown option: $1" >&2; usage >&2; exit 2 ;;
    *) break ;;
  esac
done

REPO="${1:-$HOME/doctrine.git}"
DOCTRINE_DIR="${2:-$ROOT/bot/data/doctrine}"
REPO="$(cd "$(dirname "$REPO")" 2>/dev/null && pwd)/$(basename "$REPO")" || REPO="$(cd ~ && pwd)/$(basename "$REPO")"
DOCTRINE_DIR="$(mkdir -p "$DOCTRINE_DIR" && cd "$DOCTRINE_DIR" && pwd)"

run() {
  if [ "$DRY_RUN" -eq 1 ]; then
    echo "[dry-run] $*"
  else
    "$@"
  fi
}

command -v git >/dev/null || { echo "git is required" >&2; exit 1; }
command -v rsync >/dev/null || { echo "rsync is required" >&2; exit 1; }

if [ ! -w "$DOCTRINE_DIR" ]; then
  echo "FAIL: doctrine dir is not writable: $DOCTRINE_DIR" >&2
  exit 1
fi

if [ -d "$REPO" ] && [ -f "$REPO/HEAD" ]; then
  echo "Bare repo already exists: $REPO"
else
  run git init --bare -b main "$REPO"
  echo "Created bare doctrine repo: $REPO"
fi

HOOK="$REPO/hooks/post-receive"
if [ -f "$HOOK" ] && [ "$FORCE" -eq 0 ]; then
  echo "post-receive hook already present (use --force to replace): $HOOK"
else
  run mkdir -p "$(dirname "$HOOK")"
  if [ "$DRY_RUN" -eq 0 ]; then
    cat > "$HOOK" <<HOOK
#!/usr/bin/env bash
# Auto-generated by setup-doctrine-repo.sh — sync pushed Markdown into Moneypenny.
set -euo pipefail
REPO="$REPO"
DOCTRINE_DIR="$DOCTRINE_DIR"
LOG="\${DOCTRINE_DIR}/.git-sync.log"
WORK="\$(mktemp -d)"
trap 'rm -rf "\$WORK"' EXIT

git --git-dir="\$REPO" --work-tree="\$WORK" checkout -f main
mkdir -p "\$DOCTRINE_DIR"
rsync -a --delete --prune-empty-dirs \\
  --include='*/' --include='*.md' --include='*.markdown' --exclude='*' \\
  "\$WORK"/ "\$DOCTRINE_DIR"/
COUNT=\$(find "\$DOCTRINE_DIR" -type f \\( -name '*.md' -o -name '*.markdown' \\) ! -path '*/.git-sync.log' | wc -l | tr -d ' ')
echo "\$(date -Is) synced \${COUNT} doc(s) to \$DOCTRINE_DIR" >> "\$LOG"
echo "[doctrine] synced \${COUNT} doc(s) to Moneypenny (nested paths preserved)"
HOOK
    chmod +x "$HOOK"
  fi
  echo "Installed post-receive hook: $HOOK"
fi

IP="$(hostname -I 2>/dev/null | awk '{print $1}' || true)"
cat <<MSG

Doctrine repo ready.
  bare repo:    $REPO
  doctrine dir: $DOCTRINE_DIR
  sync log:     $DOCTRINE_DIR/.git-sync.log

On a workstation (one-time):
  git clone ssh://${USER}@${IP:-<this-host>}${REPO} doctrine && cd doctrine

Publish (supports nested folders, e.g. intel/intsum.md):
  mkdir -p intel
  printf '%s\n' '---' 'classification: unclassified' '---' '# INTSUM' 'body' > intel/intsum.md
  git add . && git commit -m "doctrine update" && git push

On push, files mirror into the bot data dir; the running bot re-embeds automatically
(requires ragEnabled + the rag compose profile). Test locally:
  ./scripts/doctrine-sync-test.sh

MSG